name: PyTestLulw

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: python go bRRRRRRRRRRRRRRr
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Get deps
        run: |
          python -m pip install --upgrade pip
          pip install -r req
          python -m build . && pip install .
      - name: Analysing da code with da pytest
        run: |
          pytest
